drop table if exists history_price;
create table history_price(
  dt date comment '日期',
  gpdm char(6) comment '股票代码',
  gpmc varchar(20) comment '股票名称',
  spj decimal(10,3) comment '收盘价',
  zgj decimal(10,3) comment '最高价',
  zdj decimal(10,3) comment '最低价',
  kpj decimal(10,3) comment '开盘价',
  qsp decimal(10,3) comment '前收盘',
  zde decimal(10,3) comment '涨跌额',
  zdf decimal(10,5) comment '涨跌幅',
  hsl decimal(10,5) comment '换手率',
  cjl bigint comment '成交量',
  cjje float comment '成交金额',
  zsz float comment '总市值',
  ltsz float comment '流通市值',
  primary key (dt,gpdm)
) comment '股票的历史交易数据';

drop table if exists zfss;
create table zfss(
  dm char(9) not null comment '代码',
  gpdm char(6) not null comment '股票代码',
  gpmc varchar(20) not null comment '股票名称',
  fxdm varchar(6) comment '发行代码',
  fxrq date comment '发行日期',
  dzgfssr date comment '定增股份上市日',
  fxfs varchar(10) comment '发行方式',
  fxjg decimal(15,4) comment '发行价格',
  zfrspj decimal(10,3) comment '增发日收盘价',
  zxspj decimal(10,3) comment '最新收盘价',
  zfxjzdf float comment '自发行价涨跌幅(% 后复权)',
  zfsl_w float comment '增发数量(万股)',
  yjmjzjze_y float comment '预计募集资金总额(亿元)',
  sjmzze_y float comment '实际募资总额(亿元)',
  qz_zcmjje_y float comment '其中：资产募集金额(亿元)',
  qz_hbmjje_y float comment '其中：货币募集金额(亿元)',
  fxfy_y float comment '发行费用(亿元)',
  sjmzje_y float comment '实际募资净额(亿元)',
  fxdx varchar(35) comment '发行对象',
  rgfs varchar(10) comment '认购方式',
  zflx varchar(15) comment '增发类型',
  zfmd varchar(10) comment '增发目的',
  fxzjl float comment '发行折价率(%)',
  ssjgxdjzjgbl float comment '实施价格相对基准价格比例(%)',
  yajgxdjzjgbl float comment '预案价格相对基准价格比例(%)',
  sfkggdrg varchar(1) comment '是否控股股东认购',
  dgdrgbl float comment '大股东认购比例(%)',
  dgdrgfs varchar(10) comment '大股东认购方式',
  djjzrlx varchar(15) comment '定价基准日类型',
  djfs varchar(5) comment '定价方式',
  csyaggr date comment '初始预案公告日',
  djjzr date comment '定价基准日',
  gddhggr date comment '股东大会公告日',
  fswshggr date comment '发审委审核公告日',
  zjhshggr date comment '证监会审核公告日',
  ssggr date comment '上市公告日',
  xsjjr date comment '限售解禁日',
  zcxs varchar(100) comment '主承销商',
  cwgw varchar(100) comment '财务顾问',
  zjhhy varchar(200) comment '证监会行业',
  windhy varchar(200) comment 'Wind行业',
  zqlx varchar(5) comment '证券类型',
  gslx varchar(10) comment '公司类型'
);

drop table if exists xgfxzl;
create table xgfxzl(
  dm char(9) not null comment '代码',
  gpdm char(6) not null comment '股票代码',
  gpmc varchar(20) not null comment '股票名称',
  sgdm char(6) comment '申购代码',
  zgrq date comment '招股日期',
  wsfxrq date comment '网上发行日期',
  ssrq date comment '上市日期',
  ssb varchar(5) comment '上市板',
  fxjg decimal(15,4) comment '发行价格',
  fxsyl float comment '发行市盈率',
  xype float comment '行业PE(披露值)',
  xype_jt float comment '行业PE(近1月,静态)',
  xype_ttm float comment '行业PE(近1月,TTM)',
  fxszj_w float comment '发行数总计(万股)',
  xgfxsl_w float comment '新股发行数量(万股)',
  lgzrsl_w float comment '老股转让数量(万股)',
  wxpssl_w float comment '网下配售数量(万股)',
  wsfxsl_w float comment '网上发行数量(万股)',
  hbbl float comment '回拨比例(%)',
  wxsgsx_w float comment '网下申购上限(万股)',
  wsfxsgsx bigint comment '网上发行申购上限(股)',
  yjmz_y float comment '预计募资(上市公司)(亿元)',
  mzze_y float comment '募资总额(上市公司)(亿元)',
  mzje_y float comment '募资净额(上市公司)(亿元)',
  ssgsfxfy_w float comment '上市公司发行费用(万元)',
  ssgsfxfl float comment '上市公司发行费率(%)',
  lgzrfy_w float comment '老股转让费用(万元)',
  zrfl float comment '转让费率(%)',
  fxfyhj_w float comment '发行费用合计(万元)',
  fxfl float comment '发行费率(%)',
  cxjbjf_w float comment '承销及保荐费(万元)',
  sjjyzf_w float comment '审计及验资费(万元)',
  flfy_w float comment '法律费用(万元)',
  xxplf_w float comment '信息披露费(万元)',
  tzzsl int comment '投资者数量(家)',
  psdxsl int comment '配售对象数量(个)',
  yjsgsl_w int comment '询价申购数量(万股)',
  yjrgbs float comment '询价认购倍数',
  yxbjpsdxjs int comment '有效报价配售对象家数',
  yxbjtzzjs int comment '有效报价投资者家数',
  yxsgpsdxjs int comment '有效申购配售对象家数',
  yxsgsl_w float comment '有效申购数量(万股)',
  yxsgzj_y float comment '有效申购资金(亿元)',
  yxsghpbl float comment '有效申购获配比例(%)',
  wxrgbs float comment '认购倍数',
  yxsghs int comment '有效申购户数',
  yxsggs_w float comment '有效申购股数(万股)',
  zql float comment '中签率(%)',
  wsrgbs float comment '认购倍数',
  fxfs varchar(25) comment '发行方式',
  cxfs varchar(10) comment '承销方式',
  zcxs varchar(100) comment '主承销商',
  sjjg varchar(100) comment '审计机构',
  zcpgjg varchar(100) comment '资产评估机构',
  lssws varchar(50) comment '律师事务所',
  fxggrq date comment '发行公告日期',
  wxfxqsrq date comment '网下发行起始日期',
  wxfxjzrq date comment '网下发行截止日期',
  wsfxdjzj_y float comment '网上发行冻结资金(亿元)',
  wxpsdjzj_y float comment '网下配售冻结资金(亿元)',
  cxsrgyg_w float comment '承销商认购余股(万股)',
  mz tinyint comment '面值',
  sf varchar(10) comment '省份',
  zjhxy_2012 varchar(30) comment '证监会行业(2012版)',
  zjhxy varchar(50) comment '证监会行业',
  windxy varchar(50) comment 'Wind行业',
  zqlx char(2) comment '证券类型',
  jys char(2) comment '交易所'
) comment '新股发行资料';

drop table if exists szzz;
create table szzz(
  dt date primary key comment '日期',
  spj decimal(10,4) not null comment '收盘价',
  zgj decimal(10,4) comment '最高价',
  zdj decimal(10,4) comment '最低价',
  kpj decimal(10,4) comment '开盘价',
  qsp decimal(10,4) comment '前收盘',
  zde decimal(10,4) comment '涨跌额',
  zdf decimal(10,5) comment '涨跌幅',
  cjl bigint comment '成交量',
  cjje bigint comment '成交金额'
) comment '上证综指历史数据';

drop table if exists syzmx;
create table syzmx(
  gpsclx char(5) not null comment '股票市场类型编码 - P9705创业板;P9706综合A股市场;P9707综合B股市场;P9709综合A股和创业板;P9710综合AB股和创业板',
  dt date not null comment '交易日期',
  riskpremium1 decimal(10,6) comment '市场风险溢价因子(流通市值加权)',
  riskpremium2 decimal(10,6) comment '市场风险溢价因子(总市值加权)',
  smb1 decimal(10,6) comment '市值因子(流通市值加权)',
  smb2 decimal(10,6) comment '市值因子(总市值加权)',
  hml1 decimal(10,6) comment '账面市值比因子(流通市值加权)',
  hml2 decimal(10,6) comment '账面市值比因子(总市值加权)',
  primary key (gpsclx,dt)
) comment '三因子模型指标（日）';

drop table if exists wyzmx;
create table wyzmx(
  gpsclx char(5) not null comment '股票市场类型编码 - P9705创业板;P9706综合A股市场;P9707综合B股市场;P9709综合A股和创业板;P9710综合AB股和创业板',
  dt date not null comment '交易日期',
  tzzhlx tinyint not null comment '投资组合类型 - 1: 2*3投资组合划分方法; 2: 2*2投资组合划分方法; 3: 2*2*2*2投资组合划分方法',
  riskpremium1 decimal(10,6) comment '市场风险溢价因子(流通市值加权)',
  riskpremium2 decimal(10,6) comment '市场风险溢价因子(总市值加权)',
  smb1 decimal(10,6) comment '市值因子(流通市值加权)',
  smb2 decimal(10,6) comment '市值因子(总市值加权)',
  hml1 decimal(10,6) comment '帐面市值比因子(流通市值加权)',
  hml2 decimal(10,6) comment '帐面市值比因子(总市值加权)',
  rmw1 decimal(10,6) comment '盈利能力因子（流通市值加权)',
  rmw2 decimal(10,6) comment '盈利能力因子（总市值加权)',
  cma1 decimal(10,6) comment '投资模式因子（流通市值加权)',
  cma2 decimal(10,6) comment '投资模式因子（总市值加权)'
) comment '五因子模型指标（日）';
